#ifndef SRC_UTILS_CONFIG_H_
#define SRC_UTILS_CONFIG_H_

// TBSLAS TREE VALUES INTERPOLATION/EVALUATION TYPES
#define TBSLAS_INTERP_CHEBYSHEV 0
#define TBSLAS_INTERP_CUBIC 1

#ifndef TBSLAS_INTERP_TYPE
#define TBSLAS_INTERP_TYPE TBSLAS_INTERP_CUBIC
#endif

#endif  /* SRC_UTILS_CONFIG_H_ */
